CREATE TABLE IF NOT EXISTS ratings
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR
);

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR,
    description  VARCHAR,
    release_date TIMESTAMP,
    duration     INTEGER,
    rating_id    INTEGER REFERENCES ratings (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR,
    login    VARCHAR,
    name     VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS genres
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genres_name VARCHAR
);

CREATE TABLE IF NOT EXISTS films_likes
(
    film_id INTEGER REFERENCES films (id),
    user_id INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS friendships
(
    user_id   INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    status BOOLEAN
);

CREATE TABLE IF NOT EXISTS films_genres
(
    genre_id INTEGER REFERENCES genres (id),
    film_id  INTEGER REFERENCES films (id)
);